import { expect, test } from '@playwright/test'

for (const width of [390, 1440]) {
  test.describe(`字段校验与热点创作 ${width}px`, () => {
    test.use({ viewport: { width, height: 900 } })
    test('视频必填字段就地提示，保留草稿且不提交', async ({ page }) => {
      await page.goto('/video/new')
      const writes: string[] = []
      page.on('request', request => { if (request.method() !== 'GET') writes.push(request.url()) })
      await page.getByRole('button', { name: 'AI自动创作', exact: true }).click()
      const title = page.getByPlaceholder('为这次创作命名')
      await expect(title).toBeFocused()
      await expect(title).toHaveAttribute('aria-invalid', 'true')
      await expect(page.getByText('请填写任务标题', { exact: true })).toBeVisible()
      await title.fill('保留我的草稿')
      await expect(title).toHaveAttribute('aria-invalid', 'false')
      await page.getByRole('button', { name: 'AI自动创作', exact: true }).click()
      await expect(title).toHaveValue('保留我的草稿')
      expect(writes).toEqual([])
      await expect(page.locator('.ant-message-error')).toHaveCount(0)
    })
    test('阶段质量字段与服务配置必填校验', async ({ page }) => {
      await page.goto('/settings')
      await page.getByRole('button', { name: '添加 / 更新阶段' }).click()
      await expect(page.getByText('请填写质量配置阶段', { exact: true })).toBeVisible()
      await expect(page.locator('#stage-quality-select')).toHaveAttribute('aria-invalid', 'true')
      await page.goto('/ai-services')
      await page.getByRole('button', { name: '新增服务' }).click()
      const writes: string[] = []
      page.on('request', request => { if (request.method() !== 'GET') writes.push(request.url()) })
      await page.getByRole('button', { name: '保存 Mock 示例', exact: true }).click()
      await expect(page.getByText('请填写名称', { exact: true })).toBeVisible()
      await expect(page.getByText('请填写后端连接地址', { exact: true })).toBeVisible()
      expect(writes).toEqual([])
    })
    test('实例无效不请求，字段纠正后清除错误', async ({ page }) => {
      await page.goto('/engine')
      await page.getByRole('button', { name: '创建实例', exact: true }).click()
      const writes: string[] = []
      page.on('request', request => { if (request.method() !== 'GET') writes.push(request.url()) })
      await page.getByRole('button', { name: '保存实例', exact: true }).click()
      const name = page.getByPlaceholder('例如 Local ComfyUI')
      await expect(name).toHaveAttribute('aria-invalid', 'true')
      await expect(name).toBeFocused()
      await expect(page.getByText('请填写实例名称', { exact: true })).toBeVisible()
      await name.fill('校验实例')
      await expect(name).toHaveAttribute('aria-invalid', 'false')
      await expect(page.getByText('请填写实例名称', { exact: true })).toBeHidden()
      await page.getByPlaceholder('http://localhost:8188').fill('invalid')
      await page.getByRole('button', { name: '保存实例', exact: true }).click()
      expect(writes).toEqual([])
      await expect(page.locator('.ant-message-error')).toHaveCount(0)
    })
    test('热点选择、标题校验、创建并进入文章编辑器', async ({ page }) => {
      await page.goto('/hot-topics')
      const load = page.getByRole('button', { name: '加载演示热点', exact: true })
      if (await load.isVisible()) await load.click()
      await expect(page.getByRole('button', { name: '创建热点文章', exact: true })).toBeDisabled()
      await page.getByRole('button', { name: '选择热点并创建文章', exact: true }).first().click()
      const drawer = page.locator('.ant-drawer-content')
      const title = drawer.locator('label').filter({ hasText: '文章标题' }).locator('input')
      await title.fill(' ')
      await drawer.getByRole('button', { name: '创建热点文章并进入编辑器' }).click()
      await expect(title).toHaveAttribute('aria-invalid', 'true')
      await expect(drawer.getByText('请填写文章标题', { exact: true })).toBeVisible()
      await title.fill('热点操作回归测试')
      await expect(title).toHaveAttribute('aria-invalid', 'false')
      const outline = drawer.locator('textarea')
      await outline.fill(' ')
      await drawer.getByRole('button', { name: '创建热点文章并进入编辑器' }).click()
      await expect(outline).toHaveAttribute('aria-invalid', 'true')
      await expect(drawer.getByText('请填写创作提纲', { exact: true })).toBeVisible()
      await outline.fill('背景、已知事实、待核实信息及来源。')
      await drawer.getByRole('button', { name: '创建热点文章并进入编辑器' }).click()
      await expect(page).toHaveURL(/\/articles\/.+\?created=1/)
      await expect(page.getByText('热点文章已创建，标题与提纲已保存。请在下方编辑正文，再保存文章。')).toBeVisible()
      await expect(page.getByRole('heading', { name: '文章工作台' })).toBeVisible()
      const body = page.getByPlaceholder('开始写作…')
      await body.fill('')
      await page.getByRole('button', { name: '保存文章', exact: true }).click()
      await expect(page.getByText('文章已保存', { exact: true })).toBeVisible()
      await page.getByRole('button', { name: '生成建议', exact: true }).click()
      await expect(body).toHaveAttribute('aria-invalid', 'true')
      await expect(page.getByText('请填写文章正文', { exact: true })).toBeVisible()
      await body.fill('这是用于回归测试的人工编辑正文。')
      await expect(body).toHaveAttribute('aria-invalid', 'false')
      await page.getByRole('button', { name: '保存文章', exact: true }).click()
      await expect(page.getByText('文章已保存', { exact: true })).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    })
  })
}
