import { expect, test } from '@playwright/test'

test('quality presets remain drafts until saved, stage overrides persist independently', async ({ page }) => {
  await page.goto('/settings')
  await page.getByRole('button', { name: 'Strict · 95' }).click()
  await expect(page.locator('#threshold')).toHaveValue('95')
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await expect(page.getByText('设置已保存', { exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: '质量配置阶段' }).focus()
  await page.getByRole('combobox', { name: '质量配置阶段' }).press('ArrowDown')
  await page.getByTitle('剧本生成 · SCRIPT', { exact: true }).click()
  await page.getByRole('spinbutton', { name: '阶段质量阈值' }).fill('90')
  await page.getByRole('button', { name: '添加 / 更新阶段' }).click()
  await page.getByRole('button', { name: '保存阶段质量配置', exact: true }).click()
  await expect(page.getByText('阶段质量配置已保存', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('#threshold')).toHaveValue('95')
  await expect(page.locator('.quality-row')).toContainText('阈值 90')
  await page.getByRole('button', { name: '移除覆盖' }).click()
  await page.getByRole('button', { name: '保存阶段质量配置', exact: true }).click()
  await expect(page.getByText('阶段质量配置已保存', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('.quality-row')).toHaveCount(0)
})
