ALTER TABLE `User`
  ADD COLUMN `nickname` VARCHAR(100) NULL,
  ADD COLUMN `email` VARCHAR(254) NULL,
  ADD COLUMN `lastLoginAt` DATETIME(3) NULL;

ALTER TABLE `AuditLog`
  ADD COLUMN `ip` VARCHAR(45) NULL,
  ADD COLUMN `result` VARCHAR(32) NOT NULL DEFAULT 'SUCCESS';
