import { describe, expect, it, vi, afterEach } from 'vitest'
import type { TaskAction, VideoRequest } from '../../src/types'
import { createMockApi, PersistenceError, STORAGE_KEY } from '../../src/services/mock'
import type { StoragePort } from '../../src/services/mock'
import { allowedActions } from '../../src/services/pipeline'
import { reviewActionReason } from '../../src/services/pipeline'
import { createDemoSeed, createSeed } from '../../src/services/seed'

export class MemoryStorage implements StoragePort {
  data = new Map<string, string>()
  fail = false
  getItem(key: string): string | null { return this.data.get(key) ?? null }
  setItem(key: string, value: string): void { if (this.fail) throw new Error('quota exceeded'); this.data.set(key, value) }
}
const request: VideoRequest = { title: '测试', theme: '测试主题', type: '短剧', ratio: '9:16', duration: 30, platform: '抖音', style: '写实', characters: '甲', modelId: 'minimax-h3', workflowId: 'minimax-video-v1', scenario: 'normal' }
function setup(scenario: VideoRequest['scenario'] = 'normal') {
  const storage = new MemoryStorage()
  let time = Date.parse('2026-09-23T00:00:00Z')
  const api = createMockApi({ storage, clock: () => time })
  api.saveSettings({ ...api.getDb().settings, stageDuration: 10 })
  const task = api.createVideo({ ...request, scenario })
  return { api, storage, id: task.id, clock: () => time, step: (ms = 10) => { time += ms; api.tick() }, task: () => api.getDb().tasks[0]! }
}
afterEach(() => vi.useRealTimers())

describe('收口：独立文章、多维质量、可选阶段与恢复', () => {
  it('视频五维质量明确 Mock，阶段输出保存实际本地内容与请求', () => {
    const s = setup()
    for (let i = 0; i < 11; i++) s.step()
    const task = s.task()
    expect(task.quality?.criteria.map(c => c.name)).toEqual(['Mock 人物一致性', 'Mock 画面质量', 'Mock 动作自然度', 'Mock 连续性', 'Mock Prompt遵循'])
    expect(task.quality?.criteria.every(c => c.reason.includes('Mock'))).toBe(true)
    expect(task.stages.find(p => p.key === 'SCRIPT')?.output).toBe(task.script)
    expect(JSON.parse(task.stages.find(p => p.key === 'CHARACTER')!.output)).toEqual(task.characters)
    expect(JSON.parse(task.stages.find(p => p.key === 'STORYBOARD')!.output)).toEqual(task.shots)
    for (const stage of task.stages.filter(p => p.status === 'success')) {
      expect(JSON.parse(stage.prompt)).toEqual(task.request)
    }
  })
  it('只允许 RUNNING AUDIO/SUBTITLE skip，跳过字幕不生成字幕资产', () => {
    const s = setup()
    for (let i = 0; i < 7; i++) s.step()
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('AUDIO')
    expect(allowedActions(s.task())).toContain('skip')
    s.api.action(s.id, 'skip')
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('SUBTITLE')
    s.api.action(s.id, 'skip')
    expect(() => s.api.action(s.id, 'skip')).toThrow('非法')
    s.step()
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('QA')
    expect(() => s.api.action(s.id, 'skip')).toThrow('非法')
    s.step()
    expect(s.task().status).toBe('REVIEWING')
    expect(() => s.api.action(s.id, 'skip')).toThrow('非法')
    s.api.action(s.id, 'approve')
    expect(s.api.getDb().assets).toHaveLength(3)
    expect(s.api.getDb().assets.some(a => a.name.endsWith('.srt'))).toBe(false)
  })
  it('timeout wait 只一次，恢复当前阶段；刷新后保留次数且能完成', () => {
    const s = setup('timeout')
    s.step(); s.step(); s.step(30)
    expect(s.task().status).toBe('FAILED')
    expect(allowedActions(s.task())).toEqual(['wait', 'cancel', 'retry'])
    const before = s.task()
    s.api.action(s.id, 'wait')
    expect(s.task().status).toBe('QUEUED')
    expect(s.task().stageIndex).toBe(before.stageIndex)
    expect(s.task().stages[0]).toEqual(before.stages[0])
    expect(s.task().retries).toBe(0)
    expect(() => s.api.action(s.id, 'wait')).toThrow('非法')
    const resumed = createMockApi({ storage: s.storage, clock: s.clock })
    expect(resumed.getDb().tasks[0]?.logs.filter(l => l.message === 'TIMEOUT_WAIT_USED')).toHaveLength(1)
    expect(allowedActions({ ...s.task(), status: 'FAILED', errorType: 'timeout' })).not.toContain('wait')
    resumed.tick()
    s.api.refresh()
    for (let i = 0; i < 10; i++) s.step()
    expect(s.task().status).toBe('REVIEWING')
  })
  it('文章动态选择新的 LLM 与 text 工作流，无匹配时明确失败', () => {
    const s = setup()
    const db = s.api.getDb()
    const llm = db.models.find(m => m.capability === 'LLM')!
    llm.id = 'custom-llm'
    db.workflows = [{ ...db.workflows[0]!, id: 'custom-text', type: 'Text', active: true }]
    s.storage.setItem(STORAGE_KEY, JSON.stringify(db))
    s.api.refresh()
    const article = s.api.createArticle('topic-1')
    const task = s.api.getDb().tasks.find(t => t.id === article.taskId)!
    expect(task.modelId).toBe('custom-llm')
    expect(task.workflowId).toBe('custom-text')
    s.api.toggleModel('custom-llm')
    expect(() => s.api.createArticle('topic-1')).toThrow('LLM')
    s.api.toggleModel('custom-llm')
    s.api.saveWorkflow({ ...db.workflows[0]!, active: false })
    expect(() => s.api.createArticle('topic-1')).toThrow('文本工作流')
  })
  it('文章独立十阶段/四维质量，改稿回到文章 review，重试也不跑视频阶段', () => {
    const s = setup()
    const article = s.api.createArticle('topic-1')
    const keys = ['HOT_TOPIC', 'TOPIC', 'OUTLINE', 'GENERATE', 'ARTICLE_REVIEW', 'FACT', 'SAFETY', 'TITLE', 'ILLUSTRATION', 'FINAL_REVIEW']
    expect(s.task().stages.map(p => p.key)).toEqual(keys)
    for (let i = 0; i < keys.length; i++) s.step()
    expect(s.task().status).toBe('REVIEWING')
    expect(s.task().quality?.criteria.map(c => c.name)).toEqual(['Mock 事实', 'Mock 风险', 'Mock 结构', 'Mock 原创声明'])
    expect(s.task().characters).toEqual([])
    expect(s.task().shots).toEqual([])
    expect(s.task().stages.find(p => p.key === 'GENERATE')?.output).toBe(article.body)
    s.api.saveArticle({ ...article, body: `${article.body}\n人工改稿` })
    expect(s.task().status).toBe('WAITING')
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('ARTICLE_REVIEW')
    expect(s.task().quality).toBeNull()
    s.api.action(article.taskId, 'resume')
    for (let i = 0; i < 6; i++) s.step()
    expect(s.task().status).toBe('REVIEWING')
    s.api.action(article.taskId, 'reject')
    s.api.action(article.taskId, 'retry')
    expect(s.task().status).toBe('QUEUED')
    expect(s.task().stages.map(p => p.key)).toEqual(keys)
    expect(s.task().stageIndex).toBe(0)
  })
  it('createSeed 保持空，loadDemo 只追加且使用不同 ID，不覆盖用户配置', () => {
    expect(createSeed().tasks).toEqual([])
    expect(createDemoSeed().tasks).toHaveLength(3)
    const s = setup()
    const before = s.api.getDb()
    const first = s.api.loadDemo()
    const second = s.api.loadDemo()
    const after = s.api.getDb()
    expect(after.tasks).toHaveLength(7)
    expect(after.tasks.find(t => t.id === s.id)).toEqual(before.tasks[0])
    expect(new Set([...first, ...second].map(t => t.id)).size).toBe(6)
    expect(after.settings).toEqual(before.settings)
    expect(after.models).toEqual(before.models)
    expect(after.workflows).toEqual(before.workflows)
  })
})

describe('收口契约', () => {
  it('视频五项 Mock 评分，阶段保存真实本地内容与请求', () => {
    const s = setup()
    for (let i = 0; i < 11; i++) s.step()
    const task = s.task()
    expect(task.quality?.criteria.map(c => c.name)).toEqual(['Mock 人物一致性', 'Mock 画面质量', 'Mock 动作自然度', 'Mock 连续性', 'Mock Prompt遵循'])
    expect(task.stages.find(x => x.key === 'SCRIPT')?.output).toBe(task.script)
    expect(JSON.parse(task.stages.find(x => x.key === 'CHARACTER')!.output)).toEqual(task.characters)
    expect(JSON.parse(task.stages.find(x => x.key === 'STORYBOARD')!.output)).toEqual(task.shots)
    for (const stage of task.stages.slice(0, -1)) expect(JSON.parse(stage.prompt)).toEqual(request)
  })
  it('只跳过 AUDIO/SUBTITLE，不能跳过 QA 或最终人工门，字幕跳过后不生成字幕资产', () => {
    const s = setup()
    for (let i = 0; i < 7; i++) s.step()
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('AUDIO')
    expect(allowedActions(s.task())).toContain('skip')
    s.api.action(s.id, 'skip')
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('SUBTITLE')
    s.api.action(s.id, 'skip')
    s.step()
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('QA')
    expect(() => s.api.action(s.id, 'skip')).toThrow('非法')
    s.step()
    expect(s.task().status).toBe('REVIEWING')
    expect(() => s.api.action(s.id, 'skip')).toThrow('非法')
    s.api.action(s.id, 'approve')
    expect(s.api.getDb().assets).toHaveLength(3)
    expect(s.api.getDb().assets.some(a => a.name.endsWith('.srt'))).toBe(false)
  })
  it('timeout wait 仅一次，保持当前阶段、刷新后仍记住恢复记录', () => {
    const s = setup('timeout')
    s.step()
    s.step()
    s.step(30)
    const failed = s.task()
    expect(failed.status).toBe('FAILED')
    expect(allowedActions(failed)).toContain('wait')
    s.api.action(s.id, 'wait')
    expect(s.task().status).toBe('QUEUED')
    expect(s.task().stageIndex).toBe(failed.stageIndex)
    expect(s.task().retries).toBe(0)
    expect(s.task().stages[0]).toEqual(failed.stages[0])
    const restored = createMockApi({ storage: s.storage, clock: s.clock })
    expect(restored.getDb().tasks[0]?.logs.some(l => l.message === 'TIMEOUT_WAIT_USED')).toBe(true)
    expect(allowedActions({ ...restored.getDb().tasks[0]!, status: 'FAILED', errorType: 'timeout' })).not.toContain('wait')
    s.step()
    s.step()
    expect(s.task().stageIndex).toBe(failed.stageIndex + 1)
    for (let i = 0; i < 12; i++) s.step()
    expect(s.task().status).toBe('REVIEWING')
  })
  it('文章使用动态 LLM/text 配置、独立阶段，编辑后重新审核不走视频索引', () => {
    const storage = new MemoryStorage()
    const seed = createSeed()
    seed.models = seed.models.filter(m => m.capability === 'LLM').map(m => ({ ...m, id: 'custom-llm' }))
    seed.workflows = [{ ...seed.workflows[0]!, id: 'custom-text', type: 'Text', active: true }]
    seed.settings.stageDuration = 10
    storage.setItem(STORAGE_KEY, JSON.stringify(seed))
    let time = Date.now()
    const api = createMockApi({ storage, clock: () => time })
    const article = api.createArticle('topic-1')
    const tick = () => { time += 10; api.tick() }
    expect(api.getDb().tasks[0]?.modelId).toBe('custom-llm')
    expect(api.getDb().tasks[0]?.workflowId).toBe('custom-text')
    expect(api.getDb().tasks[0]?.stages.map(s => s.key)).toEqual(['HOT_TOPIC', 'TOPIC', 'OUTLINE', 'GENERATE', 'ARTICLE_REVIEW', 'FACT', 'SAFETY', 'TITLE', 'ILLUSTRATION', 'FINAL_REVIEW'])
    for (let i = 0; i < 10; i++) tick()
    const task = api.getDb().tasks[0]!
    expect(task.status).toBe('REVIEWING')
    expect(task.characters).toEqual([])
    expect(task.shots).toEqual([])
    expect(task.quality?.criteria.map(c => c.name)).toEqual(['Mock 事实', 'Mock 风险', 'Mock 结构', 'Mock 原创声明'])
    expect(task.stages.find(s => s.key === 'GENERATE')?.output).toBe(article.body)
    api.saveArticle({ ...article, body: '编辑后的正文' })
    expect(api.getDb().tasks[0]?.status).toBe('WAITING')
    expect(api.getDb().tasks[0]?.stages[api.getDb().tasks[0]!.stageIndex]?.key).toBe('ARTICLE_REVIEW')
    expect(api.getDb().tasks[0]?.quality).toBeNull()
    api.action(article.taskId, 'resume')
    for (let i = 0; i < 6; i++) tick()
    expect(api.getDb().tasks[0]?.status).toBe('REVIEWING')
    api.action(article.taskId, 'reject')
    api.action(article.taskId, 'retry')
    expect(api.getDb().tasks[0]?.stages[0]?.key).toBe('HOT_TOPIC')
    expect(api.getDb().tasks[0]?.status).toBe('QUEUED')
  })
  it('文章缺少启用 LLM 或 text workflow 时原子拒绝', () => {
    const s = setup()
    s.api.toggleModel('qwen-max')
    expect(() => s.api.createArticle('topic-1')).toThrow('LLM')
    s.api.toggleModel('qwen-max')
    for (const workflow of s.api.getDb().workflows) s.api.saveWorkflow({ ...workflow, active: false })
    expect(() => s.api.createArticle('topic-1')).toThrow('文本工作流')
    expect(s.api.getDb().articles).toEqual([])
  })
  it('loadDemo 仅追加三个新任务，不覆盖已有数据；基础 seed 仍为空', () => {
    const s = setup()
    const original = s.api.getDb()
    const demos = s.api.loadDemo()
    expect(demos).toHaveLength(3)
    expect(s.api.getDb().tasks).toHaveLength(4)
    expect(s.api.getDb().tasks.find(t => t.id === s.id)).toEqual(original.tasks[0])
    expect(s.api.getDb().settings).toEqual(original.settings)
    expect(s.api.getDb().topics).toEqual(original.topics)
    const more = s.api.loadDemo()
    expect(new Set([...demos, ...more].map(t => t.id)).size).toBe(6)
    expect(createSeed().tasks).toEqual([])
  })
})

describe('文章独立流水线、输出和动作边界', () => {
  it('视频五项质量评分明确 Mock，阶段保存真实本地输出和 request prompt', () => {
    const s = setup()
    for (let i = 0; i < 11; i++) s.step()
    const task = s.task()
    expect(task.quality?.criteria.map(c => c.name)).toEqual(['Mock 人物一致性', 'Mock 画面质量', 'Mock 动作自然度', 'Mock 连续性', 'Mock Prompt遵循'])
    expect(task.quality?.criteria.every(c => c.reason.includes('Mock'))).toBe(true)
    expect(task.stages.find(st => st.key === 'SCRIPT')?.output).toBe(task.script)
    expect(JSON.parse(task.stages.find(st => st.key === 'CHARACTER')!.output)).toEqual(task.characters)
    expect(JSON.parse(task.stages.find(st => st.key === 'STORYBOARD')!.output)).toEqual(task.shots)
    expect(task.stages.filter(st => st.status === 'success').every(st => JSON.parse(st.prompt).theme === request.theme)).toBe(true)
  })
  it('skip 只允许运行中的 AUDIO/SUBTITLE，不能跳过 QA 或最终门', () => {
    const s = setup()
    for (let i = 0; i < 7; i++) s.step()
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('AUDIO')
    expect(allowedActions(s.task())).toContain('skip')
    s.api.action(s.id, 'skip')
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('SUBTITLE')
    s.api.action(s.id, 'skip')
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('COMPOSE')
    expect(() => s.api.action(s.id, 'skip')).toThrow('非法')
    s.step()
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('QA')
    expect(() => s.api.action(s.id, 'skip')).toThrow('非法')
    s.step()
    expect(s.task().status).toBe('REVIEWING')
    expect(() => s.api.action(s.id, 'skip')).toThrow('非法')
    s.api.action(s.id, 'approve')
    expect(s.api.getDb().assets).toHaveLength(3)
    expect(s.api.getDb().assets.some(a => a.name.endsWith('.srt'))).toBe(false)
  })
  it('timeout wait 保留当前阶段，刷新后仅一次计数仍生效', () => {
    const s = setup('timeout')
    s.step()
    s.step()
    s.step(30)
    expect(s.task().status).toBe('FAILED')
    expect(allowedActions(s.task())).toContain('wait')
    const previous = s.task()
    s.api.action(s.id, 'wait')
    expect(s.task().status).toBe('QUEUED')
    expect(s.task().stageIndex).toBe(previous.stageIndex)
    expect(s.task().stages[0]).toEqual(previous.stages[0])
    const resumed = createMockApi({ storage: s.storage, clock: s.clock })
    expect(resumed.getDb().tasks[0]?.logs.filter(l => l.message === 'TIMEOUT_WAIT_USED')).toHaveLength(1)
    s.step()
    s.step()
    expect(s.task().stageIndex).toBe(previous.stageIndex + 1)
    // 再次出现超时失败时也不能重复 wait（通过持久化重建模拟）。
    const snapshot = s.api.getDb()
    snapshot.tasks[0]!.status = 'FAILED'
    snapshot.tasks[0]!.errorType = 'timeout'
    s.storage.setItem(STORAGE_KEY, JSON.stringify(snapshot))
    resumed.refresh()
    expect(allowedActions(resumed.getDb().tasks[0]!)).not.toContain('wait')
    expect(() => resumed.action(s.id, 'wait')).toThrow('非法')
  })
  it('文章使用动态 LLM/Text 配置，不依赖默认 ID 或 connected', () => {
    const storage = new MemoryStorage()
    const db = createSeed()
    db.models = [{ ...db.models[1]!, id: 'custom-llm', connected: false }]
    db.workflows = [{ ...db.workflows[0]!, id: 'custom-text', type: 'Text', provider: 'Mock' }]
    storage.setItem(STORAGE_KEY, JSON.stringify(db))
    const api = createMockApi({ storage })
    const article = api.createArticle('topic-1')
    const task = api.getDb().tasks.find(t => t.id === article.taskId)!
    expect(task.modelId).toBe('custom-llm')
    expect(task.workflowId).toBe('custom-text')
    expect(task.stages.map(st => st.key)).toEqual(['HOT_TOPIC', 'TOPIC', 'OUTLINE', 'GENERATE', 'ARTICLE_REVIEW', 'FACT', 'SAFETY', 'TITLE', 'ILLUSTRATION', 'FINAL_REVIEW'])
    api.toggleModel('custom-llm')
    expect(() => api.createArticle('topic-1')).toThrow('LLM')
    api.toggleModel('custom-llm')
    api.saveWorkflow({ ...db.workflows[0]!, type: 'Text to Image' })
    expect(() => api.createArticle('topic-1')).toThrow('文本')
  })
  it('文章多项 Mock 评分、内容编辑重审及 retry 都保留独立流水线', () => {
    const s = setup()
    const article = s.api.createArticle('topic-1')
    for (let i = 0; i < 10; i++) s.step()
    expect(s.task().status).toBe('REVIEWING')
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('FINAL_REVIEW')
    expect(s.task().quality?.criteria.map(c => c.name)).toEqual(['Mock 事实', 'Mock 风险', 'Mock 结构', 'Mock 原创声明'])
    expect(s.task().stages.find(st => st.key === 'GENERATE')?.output).toBe(article.body)
    expect(s.task().characters).toEqual([])
    expect(s.task().shots).toEqual([])
    s.api.saveArticle({ ...article, body: '修改后的文章内容' })
    expect(s.task().status).toBe('WAITING')
    expect(s.task().quality).toBeNull()
    expect(s.task().stages[s.task().stageIndex]?.key).toBe('ARTICLE_REVIEW')
    s.api.action(article.taskId, 'resume')
    for (let i = 0; i < 6; i++) s.step()
    expect(s.task().status).toBe('REVIEWING')
    s.api.action(article.taskId, 'reject')
    s.api.action(article.taskId, 'retry')
    expect(s.task().status).toBe('QUEUED')
    expect(s.task().stages[0]?.key).toBe('HOT_TOPIC')
    expect(s.task().stages.some(st => st.key === 'VIDEO')).toBe(false)
  })
  it('显式加载三个 demo 只追加，默认 seed 仍空且不覆盖用户数据', () => {
    const s = setup()
    expect(createSeed().tasks).toEqual([])
    expect(createDemoSeed().tasks).toHaveLength(3)
    const before = s.api.getDb()
    const demos = s.api.loadDemo()
    expect(demos).toHaveLength(3)
    expect(s.api.getDb().tasks.find(t => t.id === s.id)).toEqual(before.tasks[0])
    expect(s.api.getDb().settings).toEqual(before.settings)
    expect(s.api.getDb().topics).toEqual(before.topics)
    s.api.loadDemo()
    expect(s.api.getDb().tasks).toHaveLength(7)
    expect(new Set(s.api.getDb().tasks.map(t => t.id)).size).toBe(7)
  })
})

describe('Mock 状态机与资产', () => {
  it('REVIEWING exposes an actionable review guard, approve reaches SUCCESS, reject preserves content and trace', () => {
    const s = setup()
    for (let i = 0; i < 11; i++) s.step()
    const reviewing = s.task()
    expect(reviewing.status).toBe('REVIEWING')
    expect(reviewActionReason(s.api.getDb(), reviewing, 'approve')).toBeUndefined()
    const script = reviewing.script
    s.api.action(s.id, 'approve')
    expect(s.task().status).toBe('SUCCESS')
    expect(s.task().approved).toBe(true)
    expect(s.task().script).toBe(script)

    const rejected = setup()
    for (let i = 0; i < 11; i++) rejected.step()
    rejected.api.action(rejected.id, 'reject')
    expect(rejected.task().status).toBe('FAILED')
    expect(rejected.task().approved).toBe(false)
    expect(rejected.task().script).toContain('Mock 创作文本')
    expect(rejected.task().logs.some(log => log.message.includes('人工操作：reject'))).toBe(true)
    expect(rejected.api.getDb().traces?.some(trace => trace.taskId === rejected.id && trace.status === 'FAILED')).toBe(true)
  })

  it('review guard explains wrong status, unauthorized user, empty content, and unavailable real backend', () => {
    const s = setup()
    expect(reviewActionReason(s.api.getDb(), s.task(), 'approve')).toContain('QUEUED')
    for (let i = 0; i < 11; i++) s.step()
    const task = s.task()
    expect(reviewActionReason(s.api.getDb(), task, 'approve', { permitted: false, available: true })).toContain('tasks.update')
    expect(reviewActionReason(s.api.getDb(), task, 'approve', { permitted: true, available: false })).toContain('真实模式')
    const db = s.api.getDb()
    db.tasks[0]!.script = ''
    expect(reviewActionReason(db, db.tasks[0]!, 'approve')).toContain('为空')
    s.storage.setItem(STORAGE_KEY, JSON.stringify(db))
    expect(() => s.api.action(s.id, 'approve')).toThrow('为空')
    expect(s.api.refresh().tasks[0]!.status).toBe('REVIEWING')
    expect(reviewActionReason(s.api.getDb(), { ...task, status: 'SUCCESS' }, 'approve')).toContain('SUCCESS')
  })

  it('UI eligibility and mutation use the stage threshold rather than an unrelated global threshold', () => {
    const s = setup()
    s.api.saveSettings({ ...s.api.getDb().settings, threshold: 100 })
    s.api.saveQualityConfigs([{ stageId: 'QA', threshold: 90, enabled: true }])
    for (let i = 0; i < 11; i++) s.step()
    expect(s.task().status).toBe('REVIEWING')
    expect(reviewActionReason(s.api.getDb(), s.task(), 'approve')).toBeUndefined()
    s.api.action(s.id, 'approve')
    expect(s.task().status).toBe('SUCCESS')
  })

  it('QUEUED → RUNNING → REVIEWING → SUCCESS；只有批准后生成真实文本资产', () => {
    const s = setup()
    expect(s.task().status).toBe('QUEUED')
    s.step()
    expect(s.task().status).toBe('RUNNING')
    for (let i = 0; i < 10; i++) s.step()
    expect(s.task().status).toBe('REVIEWING')
    expect(s.api.getDb().assets).toEqual([])
    s.api.action(s.id, 'approve')
    const db = s.api.getDb()
    expect(s.task().status).toBe('SUCCESS')
    expect(db.assets).toHaveLength(4)
    expect(db.assets.every(a => a.url.startsWith('data:') && a.content)).toBe(true)
    expect(db.assets.some(a => a.type === '视频')).toBe(false)
    expect(decodeURIComponent(db.assets[0]!.url.split(',')[1]!)).toBe(s.task().script)
    expect(() => s.api.action(s.id, 'approve')).toThrow('非法')
    expect(() => s.api.action(s.id, 'retry')).toThrow('非法')
  })
  it('cancel 永久终态，tick 和所有人工操作均不能复活', () => {
    const s = setup()
    s.api.action(s.id, 'cancel')
    const actions: TaskAction[] = ['pause', 'resume', 'cancel', 'retry', 'approve', 'reject', 'skip', 'wait']
    for (const action of actions) expect(() => s.api.action(s.id, action)).toThrow('非法')
    s.step(10000)
    expect(s.task().status).toBe('CANCELLED')
    expect(s.api.getDb().assets).toHaveLength(0)
  })
  it('pause 停止推进，resume 重新排队；运行中 wait 非法', () => {
    const s = setup()
    s.step()
    s.api.action(s.id, 'pause')
    s.step(10000)
    expect(s.task().stageIndex).toBe(0)
    s.api.action(s.id, 'resume')
    expect(s.task().status).toBe('QUEUED')
    s.step()
    expect(s.task().status).toBe('RUNNING')
    expect(s.task().stageIndex).toBe(0)
    expect(() => s.api.action(s.id, 'wait')).toThrow('非法')
    s.api.action(s.id, 'pause')
    expect(s.task().status).toBe('WAITING')
  })
  it('不允许提前 approve 或 skip 绕过质量门限', () => {
    const s = setup()
    expect(() => s.api.action(s.id, 'approve')).toThrow()
    expect(() => s.api.action(s.id, 'skip')).toThrow()
    expect(() => s.api.action('missing', 'cancel')).toThrow('不存在')
  })
  it.each(['system', 'timeout'] as const)('%s 场景失败后不无限自动重试；retry 先 QUEUED', scenario => {
    const s = setup(scenario)
    s.step()
    s.step()
    s.step()
    if (scenario === 'timeout') {
      expect(s.task().status).toBe('RUNNING')
      s.step(20)
    }
    expect(s.task().status).toBe('FAILED')
    expect(s.task().errorType).toBe(scenario)
    expect(s.task().retries).toBe(0)
    s.api.action(s.id, 'retry')
    expect(s.task().status).toBe('QUEUED')
    expect(s.task().stageIndex).toBe(0)
    expect(s.task().error).toBeUndefined()
    expect(s.task().retries).toBe(1)
  })
  it('校验模型/工作流启用和模型能力', () => {
    const s = setup()
    s.api.toggleModel(request.modelId)
    expect(() => s.api.createVideo(request)).toThrow('未启用')
    s.step()
    expect(s.task().status).toBe('FAILED')
    const workflow = s.api.getDb().workflows[0]!
    s.api.toggleModel(request.modelId)
    s.api.saveWorkflow({ ...workflow, active: false })
    expect(() => s.api.createVideo(request)).toThrow('未启用')
    expect(() => s.api.createVideo({ ...request, modelId: 'qwen-max', workflowId: 'storyboard-v2' })).toThrow('Video')
  })
  it('saveTask 只允许内容字段，不能伪造 SUCCESS', () => {
    const s = setup()
    s.api.action(s.id, 'pause')
    s.api.saveTask({ ...s.task(), status: 'SUCCESS', progress: 100, retries: 500, script: '人工文本' })
    expect(s.task().status).toBe('WAITING')
    expect(s.task().retries).toBe(0)
    expect(s.task().script).toBe('人工文本')
  })
  it('文章安全项未核实不能批准；批准生成文章资产', () => {
    const s = setup()
    const article = s.api.createArticle('topic-1')
    for (let i = 0; i < 11; i++) s.step()
    expect(() => s.api.action(article.taskId, 'approve')).toThrow('安全检查')
    s.api.saveArticle({ ...article, safety: [{ name: '来源', status: '通过', reason: '人工核查' }] })
    s.api.action(article.taskId, 'approve')
    expect(s.api.getDb().assets.find(a => a.taskId === article.taskId)?.content).toBe(article.body)
    expect(() => s.api.saveArticle(article)).toThrow('终态')
  })
})

describe('质量门限与有限自动重试', () => {
  it('默认质量场景自动重试两次后 FAILED，失败证据留在日志', () => {
    const s = setup('quality')
    for (let i = 0; i < 60; i++) s.step()
    expect(s.task().status).toBe('FAILED')
    expect(s.task().retries).toBe(2)
    expect(s.task().quality?.score).toBe(85)
    expect(s.task().logs.filter(l => l.level === 'error')).toHaveLength(3)
  })
  it('门限相等通过，重试产生改进评分；排队状态可观察', () => {
    const s = setup('quality')
    s.api.saveSettings({ ...s.api.getDb().settings, threshold: 75 })
    for (let i = 0; i < 11; i++) s.step()
    expect(s.task().status).toBe('QUEUED')
    expect(s.task().retries).toBe(1)
    for (let i = 0; i < 11; i++) s.step()
    expect(s.task().status).toBe('REVIEWING')
    expect(s.task().quality?.score).toBe(75)
  })
  it.each([{ autoRetry: false, maxIterations: 10 }, { autoRetry: true, maxIterations: 1 }])('autoRetry/maxIterations 独立限制 $autoRetry/$maxIterations', settings => {
    const s = setup('quality')
    s.api.saveSettings({ ...s.api.getDb().settings, ...settings })
    for (let i = 0; i < 30; i++) s.step()
    expect(s.task().status).toBe('FAILED')
    expect(s.task().retries).toBe(0)
  })
  it('审核期间提高门限，不能使用旧评分批准', () => {
    const s = setup()
    for (let i = 0; i < 11; i++) s.step()
    s.api.saveSettings({ ...s.api.getDb().settings, threshold: 100 })
    expect(() => s.api.action(s.id, 'approve')).toThrow('门限')
    s.api.action(s.id, 'reject')
    s.api.action(s.id, 'retry')
    expect(s.task().status).toBe('QUEUED')
  })
})

describe('持久化与单一 tick', () => {
  it('读取/写入异常明确，失败事务不更新内存，不覆盖旧数据', () => {
    const s = setup()
    const before = s.api.getDb()
    s.storage.fail = true
    expect(() => s.api.action(s.id, 'cancel')).toThrow(PersistenceError)
    expect(s.api.getDb()).toEqual(before)
    s.storage.data.set(STORAGE_KEY, '{bad')
    expect(() => s.api.refresh()).toThrow('读取')
    expect(s.api.getDb()).toEqual(before)
    expect(s.storage.getItem(STORAGE_KEY)).toBe('{bad')
  })
  it('拒绝旧版本和结构损坏数据，不静默重置', () => {
    const storage = new MemoryStorage()
    storage.setItem(STORAGE_KEY, JSON.stringify({ version: 1 }))
    expect(() => createMockApi({ storage }).getDb()).toThrow('版本')
  })
  it('新实例恢复运行，审核不自动批准；资产无重复', () => {
    const s = setup()
    s.step()
    s.step()
    const resumed = createMockApi({ storage: s.storage, clock: s.clock })
    expect(resumed.getDb()).toEqual(s.api.getDb())
    for (let i = 0; i < 9; i++) s.step()
    resumed.refresh()
    expect(resumed.getDb().tasks[0]?.status).toBe('REVIEWING')
    resumed.tick()
    expect(resumed.getDb().assets).toHaveLength(0)
    resumed.action(s.id, 'approve')
    const final = createMockApi({ storage: s.storage })
    final.tick()
    expect(final.getDb().assets).toHaveLength(4)
  })
  it('seed 与快照隔离，reset 不复用变异对象', () => {
    const s = setup()
    const snapshot = s.api.getDb()
    snapshot.settings.threshold = 0
    expect(s.api.getDb().settings.threshold).toBe(90)
    s.api.reset()
    expect(s.api.getDb().tasks).toHaveLength(0)
    expect(s.api.getDb().settings.stageDuration).toBe(2200)
  })
  it('重复订阅只启动一个 interval，最后退订清理；tick 错误上报并停止', () => {
    vi.useFakeTimers()
    const s = setup()
    const report = vi.fn()
    const stop1 = s.api.subscribe(vi.fn(), report)
    const stop2 = s.api.subscribe(vi.fn(), report)
    expect(vi.getTimerCount()).toBe(1)
    stop1()
    expect(vi.getTimerCount()).toBe(1)
    s.storage.fail = true
    vi.advanceTimersByTime(250)
    expect(report).toHaveBeenCalledOnce()
    expect(vi.getTimerCount()).toBe(0)
    stop2()
  })
})
